### ISSUE TITLE
To Do sort

### ISSUE THREAD

**Issue by vogelap** [Newbrict/obsidian-obligator#12]
As a user, it would be useful to have Obsidian automatically move a to-do item to the top/bottom (user configurable) of the note when the to-do item (and all associated sub-items) is marked COMPLETE. If the to-do item has any incomplete sub-items, the to-do item & sub-items would NOT be moved until the entire task (to-do item AND all sub-items) are complete.

A user-configurable option determines if the completed to-do item goes to the **top** or the **bottom** of the note (I prefer to have my completed to-do items go to the _top_ of the note).

This would mirror the functionality in the **Todo Sort** plugin (https://github.com/ryangomba/obsidian-todo-sort), and reduce the number of plugins needed to run Obsidian.

**Comment by Newbrict** [comment]
I'm personally not too interested in this feature because Obligator supports organizing your to-dos into headings and subheadings.

Also, regarding #13, which is related, checked items are intended to be wiped away at the start of a new note, unless it would break the hierarchy of items (i.e. a parent checked off but not the children). That's why there is a new note made every day while retaining the old notes -- so that each day you start with a fresh view of your obligations, but with the freedom to look back in the history to see what's been done.

**Comment by Newbrict** [comment]
I've decided that I do not want to write this feature into Obligator. I want to avoid live manipulation of active text, as that's not the purpose of Obligator.

Sorry.

**Comment by vogelap** [comment]
That is perfectly fine with me! I very much appreciate that you considered it. Plus, since the functionality exists in another plugin, it does not need to be re-produced.
