### ISSUE TITLE
question regarding the next-note feature

### ISSUE THREAD

**Issue by kl2111** [Newbrict/obsidian-obligator#16]
Thank you very much for providing the plugin. I have a question regarding the next-note feature. I configured the previous-note and next-note according to the template. The previous-note is effective and can recognize the previous diary, but the next-note cannot be recognized. My method of operation is that I created Diary A the day before yesterday, Diary B yesterday, and Diary C today. In Diary B, I can recognize A as the previous-note, but I cannot recognize C as the next-note. Is my understanding of this function correct, and how should I adjust it?

![20231120_0926Google Chromeobsidian-obligatorexampledaily_note md at master · Newbrictobsidian-obligator](https://github.com/Newbrict/obsidian-obligator/assets/66360035/cf0cccff-8825-431b-aa8d-d662904467ae)

**Comment by Newbrict** [comment]
@kl2111 Does this help explain what's going on? The next_note template is not filled in until you create your next note because I have no way of knowing when you will create the next note beforehand. Tt stays as a template macro in your current note until then.

Does that answer your question or am I misunderstanding?
