### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by msdosfx** [Newbrict/obsidian-obligator#17]
This plugin is exactly what I am looking for, but some elaboration on how to use it in your documentation would be much appreciated. I would be happy to donate for your time. I have read the documentation and the example file several times but I am still at a loss for a few things. 

- Do you turn off the Daily Note plug-in to use this plug-in? 
-  If not, I assume you have the same template file for both this plugin and the Daily Notes Plugin
- My Daily Note consists of a journal entry, a checklist that recurs every day (stretch, workout, read, etc), a rollover checklist of ToDo's, and some To Do's recurring weekly, monthly etc. I think I can finally discern the logic of the {{ obligate * * * }} macro after reading some, and finding that day of the week is 0-6 not 1-7. I just think I am doing something wrong b/c the daily note just copies the text of the macro without doing anything. Like, if it is in the daily note template, isn't the list item going to show up every day, not just when the macro indicates it should recur?

**Comment by Newbrict** [comment]
Hello,


Obligator does not depend on Daily Note in any way, so whether it's disabled or not doesn't affect Obligator.

You should create a template file dedicated for Obligator because Obligator adds many macros not supported by Daily Note.

See this basic example for the obligate macro:

```md
{{ obligate 1 * * }}
- [ ] this checkbox will be added on the first of every month.
```

Obligator analyzes the template file, and the time of the last note in order to decide whether or not to include the line that immediately proceeds the {{ obligate }} macro.

It will not add the macro ever, but it will add the line immediately after if the scheduling condition is met.


The Obligator note is created by clicking the carrot icon on the ribbon, which is on the right of the screen on desktop. 

I will look into the 0-6 weekday on Monday, if that's the case, it's a bug.

Hope that helps. If you're still confused, feel free to ask further questions.

**Comment by Newbrict** [comment]
@msdosfx Did this answer your question?
