### ISSUE TITLE
Error: "Couldn't find the Obligation header in the last note aborting"

### ISSUE THREAD

**Issue by TjeerdA** [Newbrict/obsidian-obligator#2]
I consistently get "Couldn't find the Obligation header in the last note aborting"
What am I doing wrong? 
I like the the concept of the plugin. But obviously have not managed to make it work.

**Comment by Newbrict** [comment]
Hi @TjeerdA 

I think what's going on is that you probably have a note in the "new file location" directory
![image](https://github.com/Newbrict/obsidian-obligator/assets/1683041/5dc23726-ee18-40fe-8f63-c5058dfad0f0)


Which matches the date format you used:
![image](https://github.com/Newbrict/obsidian-obligator/assets/1683041/7cfa9d09-beac-4f30-8715-bf4657c00cbc)


But it does not have the "Obligation Heading" in the note, i.e.:
![image](https://github.com/Newbrict/obsidian-obligator/assets/1683041/0e4d65c0-288f-4463-be3d-d816a7e57335)



The initial setup can be a bit awkward if you have existing notes. To fix this, you will have to add the "obligation heading" to your most recent note, so that Obligator knows what to copy over. If you don't want anything copied over.

I think I will try to simplify the way this works for the future.

**Comment by Newbrict** [comment]
If that doesn't help, can you post your template file and a screenshot of your settings page?

**Comment by TjeerdA** [comment]
It helped and worked. It seems to work exactly as hoped. The 'trick' for me is to start in a new directory /Journaling, create the first daily note there, play with the desired frontmatter and template until satisfied, and then move your daily notes to the original location (also in the settings)

Alternatively, just provide an example daily note + template with front matter that can be used as inspiration to add to your last existing daily note. In my case, although it was simple, I could not fully oversee what the plugin was expected to do. 

Thanks for the work!

**Comment by Newbrict** [comment]
Glad it's working now :)

I did include an example template file and a screenshot of the settings page to try to help with this, but I think you're right that I have to make the documentation better. I will be simplifying how it all works soon.

**Comment by Newbrict** [comment]
I did in fact simplify the settings by removing the heading option.

This changes how the plugin works slightly. It now copies over everything from the beginning of the file until the terminal heading. (rather than between two headings)

It should not affect your current setup, as it's backwards compatible. You may delete the top level heading if you didn't want it, though.

**Comment by Newbrict** [comment]
> Alternatively, just provide an example daily note + template with front matter that can be used as inspiration to add to your last existing daily note. In my case, although it was simple, I could not fully oversee what the plugin was expected to do.

I added a gif to show how to do this.
